"""
Synthesizer Agent

This agent is the fourth and final analytical agent in the pipeline. It combines
all previous analyses into a comprehensive, coherent executive summary report.

Role in Workflow:
- Fourth agent in sequential pipeline
- Integrates all previous agent outputs
- Creates final report for human review
- Last agent before human-in-the-loop approval gate

LangGraph Node Behavior:
- Receives State with claims, methodology, and limitations
- Returns State with 'final_report' field populated
- Produces structured, professional report
"""

from langchain_ollama import ChatOllama
from ..state import State, validate_state_for_synthesis


def synthesizer_agent(state: State) -> State:
    """
    Synthesize all analyses into a comprehensive executive summary.

    This agent combines outputs from all previous agents (Claims Extractor,
    Methodology Analyzer, Limitations Finder) into a coherent, structured
    report that provides an overall assessment of the research paper.

    The report includes:
    - Executive summary of key findings
    - Overview of main claims and contributions
    - Methodology strengths and characteristics
    - Notable limitations and considerations
    - Overall assessment and significance

    Args:
        state: Current workflow state with all previous analyses

    Returns:
        Updated state with 'final_report' field populated

    State Updates:
        - final_report: Comprehensive synthesized report
        - current_step: Updated to "synthesis_complete"

    Validation:
        Checks that all required analyses are present before synthesis
    """

    print("\n" + "=" * 70)
    print("[Step 4/4] Synthesizer Agent 📝")
    print("Synthesizing comprehensive analysis report...")
    print("=" * 70)

    # Validate that we have all required inputs
    # This prevents synthesis from running with incomplete data
    if not validate_state_for_synthesis(state):
        error_msg = "Cannot synthesize: Missing required analyses"
        print(f"\n❌ {error_msg}")
        print("Required: claims, methodology, limitations")

        return {
            **state,
            "final_report": "[Error: Incomplete analysis data for synthesis]",
            "current_step": "synthesis_error",
            "error_message": error_msg
        }

    # Initialize LLM
    # The .stream() method used below handles the streaming behavior.
    llm = ChatOllama(
        model="llama3",
        temperature=0.6  # Higher temp for more natural writing
    )

    # Construct comprehensive prompt with all analyses
    prompt = f"""You are an expert research analyst creating an executive summary report.

You have received detailed analyses of a research paper from specialist agents.
Synthesize these analyses into a comprehensive, well-structured report.

Your report should include:

1. **Executive Summary** (2-3 paragraphs)
   - High-level overview of the research
   - Key takeaways and significance

2. **Main Claims and Contributions**
   - Summary of primary claims
   - Novel contributions to the field

3. **Methodology Overview**
   - Key methodological approaches
   - Strengths of the research design

4. **Notable Limitations**
   - Significant limitations to consider
   - Impact on conclusions

5. **Overall Assessment**
   - Research quality and rigor
   - Significance and potential impact
   - Recommendations for readers

Use professional academic tone. Be balanced and objective.

---

CLAIMS ANALYSIS:
{state['claims']}

---

METHODOLOGY ANALYSIS:
{state['methodology']}

---

LIMITATIONS ANALYSIS:
{state['limitations']}

---

Paper Title: {state.get('paper_title', 'Unknown')}

SYNTHESIZED REPORT:"""

    try:
        print("\n📄 Generating comprehensive report...\n")

        chunks = []
        for chunk in llm.stream(prompt):
            content = chunk.content if hasattr(chunk, 'content') else str(chunk)
            print(content, end="", flush=True)
            chunks.append(content)

        print("\n")

        final_report = "".join(chunks)

        # Add header to final report for better formatting
        formatted_report = f"""
{'=' * 70}
RESEARCH PAPER ANALYSIS REPORT
{'=' * 70}

Paper: {state.get('paper_title', 'Unknown')}
Generated by: LangGraph Multi-Agent Analyzer

{final_report}

{'=' * 70}
End of Report
{'=' * 70}
"""

        return {
            **state,
            "final_report": formatted_report,
            "current_step": "synthesis_complete"
        }

    except Exception as e:
        error_msg = f"Error in Synthesizer Agent: {str(e)}"
        print(f"\n❌ {error_msg}\n")

        return {
            **state,
            "final_report": f"[Error: Could not synthesize report - {str(e)}]",
            "current_step": "synthesis_error",
            "error_message": error_msg
        }


def create_synthesis_prompt(claims: str, methodology: str,
                            limitations: str, paper_title: str) -> str:
    """
    Create optimized prompt for report synthesis.

    Helper function for prompt construction. Separating this allows
    for easier testing and prompt refinement.

    Args:
        claims: Claims analysis from Claims Extractor
        methodology: Methodology analysis from Methodology Analyzer
        limitations: Limitations analysis from Limitations Finder
        paper_title: Title of the research paper

    Returns:
        Formatted synthesis prompt
    """
    return f"""You are an expert research analyst creating an executive summary report.

Synthesize the following analyses into a comprehensive report for: "{paper_title}"

Include:
1. Executive Summary (2-3 paragraphs)
2. Main Claims and Contributions
3. Methodology Overview
4. Notable Limitations  
5. Overall Assessment

Use professional academic tone. Be balanced and objective.

---
CLAIMS: {claims}
---
METHODOLOGY: {methodology}
---
LIMITATIONS: {limitations}
---

SYNTHESIZED REPORT:"""